version: '3.9'

services:
  backend:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:6666
    volumes:
      - .:/stocks_products
    ports:
      - "8888:6666"  # Исправлен порт на 8888
    depends_on:
      - postgres
    networks:
      - mynetwork



  postgres:
    image: postgres
    environment:
      POSTGRES_DB: cicd_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

    

  nginx:
    image: nginx
    ports:
      - "3333:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - mynetwork



  redis:
    image: "redis:alpine"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge